---
title: "flat_importations.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# parallel_import
    
```{r development-parallel_import}
# You can prepare the code of the parallel_import() function here
```
  
```{r function-parallel_import}
#' Import a collection of datasets into the Global Environment (parallelized)
#' @param file_paths Character. Vector of valid absolute file paths of
#' datasets to import. File names must be unique.
#' @return After jobs completion, see the datasets imported in the Global Environment
#' @export
#'
parallel_import <- function (file_paths) {

  if (isFALSE(all(file.exists(file_paths)))) {
    
    noexist <- file_paths[! file.exists(file_paths)]
    print("These file_paths doesn't exist; check again: ")
    print(noexist)
    stop("All file_paths must be valid")
  }
  
  if (isFALSE(length(unique(basename(file_paths))) == length(file_paths))) {
    
    duplnames <- basename(file_paths)[duplicated(basename(file_paths))]
    print("These file names are duplicated at least once: ")
    print(duplnames)
    stop("File names must be unique")
  }
  
  # For each absolute file path inputted, launch a background job that
  # imports the data set mentioned in the corresponding path;
  # the R object being the file name itself:
  purrr::map(file_paths,
             \(x) {job::job({

               assign(
                 basename(x),
                 rio::import(x),
                 pos = - 1L)

               invisible()
             }, title = paste0("Importation of ",
                               basename(x)))
             })
}
```
  
```{r example-parallel_import}
mydir <- system.file("permadir_examples_and_tests/importations", package = "scrutr")
lfiles <- list.files(mydir, full.names = TRUE)

if (isTRUE(rstudioapi::isAvailable())) {
  parallel_import(lfiles)} else {
    message("This function works only in RStudio.")
  }
```
  
```{r tests-parallel_import}
test_that("Valid outputs are consistent", {
  
  # This test will not pass within RStudio but will in checks: 
  expect_false(
    object = rstudioapi::isAvailable())
})

test_that("Errors are consistent", {
  
  mydir <- system.file("permadir_examples_and_tests/importations", package = "scrutr")
  lfiles_nodupl_invalid <- c(list.files(mydir, full.names = TRUE), 
                             file.path(mydir, "novalid", "cars2.rds"))
  lfiles <- list.files(mydir, recursive = TRUE, full.names = TRUE)
  
  expect_error(
    object = parallel_import(lfiles), 
    regexp = "File names must be unique")
  
  expect_error(
    object = parallel_import(lfiles_nodupl_invalid), 
    regexp = "All file_paths must be valid")
})
```
  
# serial_import
    
```{r development-serial_import}
# You can prepare the code of the serial_import() function here
```
  
```{r function-serial_import}
#' Import a collection of datasets into the Global Environment (serialized)
#' @param file_paths Character. Vector of valid absolute file paths of
#' datasets to import
#' @return After completion, see the datasets imported in the Global Environment
#' @importFrom magrittr %>%
#' @export
#'
serial_import <- function (file_paths) {
  
  if (isFALSE(all(file.exists(file_paths)))) {
    
    noexist <- file_paths[! file.exists(file_paths)]
    print("These file_paths doesn't exist; check again: ")
    print(noexist)
    stop("All file_paths must be valid")
  }
  
  if (isFALSE(length(unique(basename(file_paths))) == length(file_paths))) {
    
    duplnames <- basename(file_paths)[duplicated(basename(file_paths))]
    print("These file names are duplicated at least once: ")
    print(duplnames)
    stop("File names must be unique")
  }
  
  # For each absolute file path inputted, launch a background job that
  # imports the data set mentioned in the corresponding path;
  # the R object being the file name itself:
  
  purrr::map(file_paths,
             \(x) {
               
               assign_to_global(basename(x),
                      rio::import(x))
               invisible()
             })
}
```
  
```{r example-serial_import}
library(magrittr)
mydir <- system.file("permadir_examples_and_tests/importations", package = "scrutr")
lfiles <- list.files(mydir, full.names = TRUE) %>% 
  (\(x) x[stringr::str_detect(x, "\\.rds$")])

# Launch this code and check your global env, 
# cars.rds and mtcars.rds should be there: 
serial_import(lfiles)
```
  
```{r tests-serial_import}
test_that("Valid outputs are consistent", {

  library(magrittr)
  mydir <- system.file("permadir_examples_and_tests/importations", package = "scrutr")
  lfiles <- list.files(mydir, full.names = TRUE) %>% 
    (\(x) x[stringr::str_detect(x, "\\.rds$")])

  expect_equal(
    object = serial_import(lfiles), 
    expected = list(NULL, NULL))
})

test_that("Errors are consistent", {
  
  mydir <- system.file("permadir_examples_and_tests/importations", package = "scrutr")
  lfiles_nodupl_invalid <- c(list.files(mydir, full.names = TRUE), 
                             file.path(mydir, "novalid", "cars2.rds"))
  lfiles <- list.files(mydir, recursive = TRUE, full.names = TRUE)
  
  expect_error(
    object = serial_import(lfiles), 
    regexp = "File names must be unique")
  
  expect_error(
    object = serial_import(lfiles_nodupl_invalid), 
    regexp = "All file_paths must be valid")
})
```
    
    
```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_importations.Rmd", 
               vignette_name = NA)
```

