---
title: "flat_convert_all.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# convert_all

```{r function-convert_all}
#' Convert all datasets within a folder to a given file format
#'
#' @param input_folderpath Character 1L. Folder path containing datasets to convert. 
#'    Datasets must be at the root of the folder
#' @param considered_extensions Character. File extensions to consider for conversion within the folder.
#'    Must be supported by the rio:: package
#' @param to Character 1L. The destination output format. 
#'    Must be supported by the rio:: package
#' @param output_folderpath Character 1L. Folder path where converted file should be placed
#' @return This function, for RStudio only, launches one background job for each file to convert
#' @export
#'
convert_all <- function(input_folderpath, considered_extensions, 
                        to, output_folderpath = input_folderpath) {
  
  if (! dir.exists(input_folderpath)) stop("input_folderpath must be a valid path")
  if (! is.character(considered_extensions)) stop("considered_extensions must be a character vector")
  if (! is.character(to)) stop("to must be a 1L character vector")
  if (! dir.exists(output_folderpath)) stop("output_folderpath must be a valid path")
  
  ext <- paste0(paste0("\\.", considered_extensions, "$"), collapse = "|")
  
  lfiles <- list.files(input_folderpath, full.names = TRUE)
  lfiles <- lfiles[grepl(ext, lfiles)]
  
  lapply(lfiles, \(l) {
    
    ext <- ext
    to <- to
    output_folderpath <- output_folderpath
    
    job::job({
      
      data <- rio::import(l, trust = TRUE)
      data <- dplyr::mutate_all(
        data, \(y) {y[nchar(as.character(y)) == 0] <- NA ; y})
      data <- dplyr::mutate_if(data, is.character, \(c) stringr::str_trim(c))
      
      rio::export(
        data, 
        file.path(output_folderpath, gsub(ext, paste0(".", to), basename(l))))
      
      job::export("none")
    }, title = paste0("Conversion of ", basename(l)))
  })
}
```

```{r examples-convert_all}
mydir <- system.file("permadir_examples_and_tests/convert_all", package = "scrutr") 

list.files(mydir)

if (rstudioapi::isAvailable()) {
convert_all(input_folderpath = mydir, considered_extensions = c("rds", "csv"), 
            to = "parquet", output_folderpath = mydir)

list.files(mydir)

unlink(file.path(mydir, c("original_cars.parquet", "original_mtcars.parquet")))
}
```

```{r tests-convert_all}
test_that("Valid outputs are consistent", {
  
  # Not possible to test in background because the function needs RStudio: 
  expect_false(object = rstudioapi::isAvailable())
})

test_that("Errors are consistent", {
  
  mydir <- system.file("permadir_examples_and_tests/convert_all", package = "scrutr")
  
  expect_error(convert_all(input_folderpath = "noexist"),
               regexp = "input_folderpath must be a valid path")
  
  expect_error(convert_all(input_folderpath = mydir, considered_extensions = 1),
               regexp = "considered_extensions must be a character vector")
  
  expect_error(convert_all(input_folderpath = mydir, 
                           considered_extensions = c("rds", "csv"),
                           to = 1),
               regexp = "to must be a 1L character vector")
  
  expect_error(convert_all(input_folderpath = mydir, 
                           considered_extensions = c("rds", "csv"),
                           to = "parquet", output_folderpath = "noexist"),
               regexp = "output_folderpath must be a valid path")
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_convert_all.Rmd", vignette_name = NA)
```

